### ISSUE TITLE
Can you provide a video regarding how to use the application?

### ISSUE THREAD

**Issue by sidghimire** [Niger-Volta-LTI/yoruba-voice-speech-recorder#1]
Hi, Love the work and would really appreciate if you showed us how to use the application

Sincere regards

**Comment by ruohoruotsi** [comment]
Hi Sid, thank you for the issue ... yes, good idea to have a visual tutorial. Are you more interested in how to elicit & record speech utterances with the app, or more how to get it running from the repo?

**Comment by sidghimire** [comment]
I would love to know how to get it up and running from the repo itself

**Comment by ruohoruotsi** [comment]
Okay, have you already tried the steps in the Readme? If so did you get stuck anything or it just wasn't clear?

On a technical note, what platform/OS are you on?
